version: '3.9'

services:
 backend:
  build: .
  ports:
   - "3000:3000"
  volumes:
   - .:/app
   - /app/node_modules

 db:
  image: mongo:latest
  restart: always
  environment:
   MONGO_INITDB_ROOT_USERNAME: troyka
   MONGO_INITDB_ROOT_PASSWORD: troy1914
  command: mongod --auth --bind_ip_all

  volumes:
   - ./db_data:/data/db
  ports:
   - "27017:27017"